### ISSUE TITLE
Documentation for GDPR compliant setup

### ISSUE THREAD

**Issue by basisbit** [bigbluebutton/bigbluebutton.github.io#136]
The goal of this issue is to collect suggestions + tasks for a documentation page on how to set up BBB in compliance to GDPR and similar data privacy & protection regulations around the world.

### Tasks
- [x] collect various configuration files where to change logging settings to not log any "private" / person-identifiable data and how to change them
- [x] collect various places where legally required data (contact data, Terms of Service,....) can be added to Greenlight, BigBlueButton and the various BBB-Plugins
- [x] create best practices documentation and explain how to set up the system so that a BBB-service can be operated in compliance with GDPR or similar regulations

### Results so far
- Logfiles for nginx: `/var/log/nginx/*` can be changed to only log `ERROR` in `/etc/nginx/sites-enabled/bigbluebutton` and `/etc/bigbluebutton/nginx/*`
- `sed -i 's/  access_log.*/access_log  \/dev\/null;/g' /etc/nginx/sites-available/bigbluebutton`
- `sed -i 's/  error_log.*/error_log \/dev\/null;/g' /etc/nginx/sites-available/bigbluebutton`
- freeswitch? `/opt/freeswitch/conf/vars.xml` - logs to `/opt/freeswitch/var/log/freeswitch`
- meteor/nodejs? - how to limit/disable? Is this what logs to `/var/log/tomcat7`?
- red5 ? logs to `/var/log/red5` - how to limit/disable?
- Kurento logs to `/var/log/kurento-media-server` - how to limit/disable?
- bbb-webrtc logs to `/var/log/bbb-webrtc-sfu` - can be disabled by setting log.level: none in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`
- Logging best practice: set `appLogLevel=Error` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
- if recording feature is not needed, set `disableRecordingDefault=true` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` and also `breakoutRoomsRecord=false` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
- consider setting `keepEvents=false` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
- set your own STUN server `stunServers: \[\x27stun:.*/stunServers: \[\x27stun:stun.yourdomain.tld:3478\x27\],` in `/usr/share/meteor/bundle/programs/web.browser/app/compatibility/sip.js` so that BBB-HTML5 client users don't send data to Google without consent
- set your custom stun/turn instead of Freeswitch STUN `sed -i 's/stun:stun.freeswitch.org/stun:stun.yourdomain.tld/g' /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`
- in `/etc/cron.daily/bigbluebutton` set `history=1` and `unrecorded_days=1` and `published_days=1` and `log_history=1` or similar values and also uncomment the line `remove_raw_of_published_recordings` close to the ending of the file, so that recording raw data actually gets deleted (if you didn't completely disable recording) 
- customize Greenlight to contain your Terms of Service documentation and also a data protection and data processing information documentation: [Greenlight code customization](https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page) and [Greenlight Terms of Services](https://docs.bigbluebutton.org/greenlight/gl-config.html#adding-terms-and-conditions)

Would be nice if more people could help and add their suggestions and so on in this issue here, so that a good quality documentation can be created.

**Comment by ichdasich** [comment]
I would add, logging wise:
- the coturn logs on the turn server; So far I could only disable this by making it log to /dev/null

and recording wise:
- Obtaining consent for recordings before users join the meeting with enabled recordings (should be documented that this is a _frontend_ task though; Should also be implemented in greenlight) and document record=true/false implications
- Complex: think about a feature that lets frontends hand over a 'recorded_consent' feature, which if falls leads to the exclusion of the specific user from recordings when joining a room
- persistence of cache-files on-disk by default (esp. the freeswitch/kurento caches in addition to the raw files)
- For the recordings, a feature to immediately delete caches after processing
- documentation that recordings are, by default, always public, even if they are not listed, and how to leviate that (e.g. https://github.com/ichdasich/bbb-rec-perm)

**Comment by basisbit** [comment]
@ichdasich could you maybe add the configuration files locations and what setting names to change for some of your suggestions?

**Comment by ichdasich** [comment]
Will do so in the next days (exam grading time atm). Question is whether it might not make more sense to create a repo for this to keep things structured.

**Comment by zner0L** [comment]
If users opt to keep recording files and logs, they should know and change:
- the duration for which to keep to keep the recording files in /etc/cron.daily/bigluebutton
- the logrotate setttings in /etc/logrotate.d

Also, I think the default values should be clearly documented somewhere, so that users can incorporate them into their privacy policy, maybe even in a sample policy. I think it might be enough to write a short policy omitting most of the legal gibberish and only mentioning the important information about which (categories of) data is kept for how long and for what (technical) reason. Though I am unsure of the legal problems you might get for providing a sample policy…

In Greenlight, room URLs contain the username of the owner, which might also be private data. Solving this depends on https://github.com/bigbluebutton/greenlight/issues/1057

**Comment by zner0L** [comment]
I would generally say this documentation is also useful for non-EU users for whom the GDPR might not be relevant, but privacy feature are. Some users could choose to implement privacy features without being legally forced to do so ;) So maybe lets not (only) call this a GDPR compliant setup but rather a user privacy documentation.

**Comment by scg-on-github** [comment]
I am just working on a compilation of data being processed in order to create a privacy statement for BBB according to GDPR. So I'm highly motivated to support your effort.

**Comment by ichdasich** [comment]
@scg-on-github See the (not yet GDPR compliant) one based on the one of bbb.com used on the instance I am running here: https://bbb.surfcloud.nl/b/terms

Will now setup a small repo for the doc, so we can actually have some structure in the data collection.

**Comment by ichdasich** [comment]
Ok, put up the repo here: https://github.com/ichdasich/bbb-privacy 

Will now integrate all information from this ticket.

**Comment by ichdasich** [comment]
ok, information from the ticket should be in; Will do a swipe tonight to fill all the empty parameters we have there atm.

**Comment by ffdixon** [comment]
Just following this issue -- this is good work guys.  Once you have something ready, we'd like to merge it into the official docs.  https://github.com/bigbluebutton/bigbluebutton.github.io

**Comment by ichdasich** [comment]
As it already contains contributions from @basisbit and @zner0L ; We should maybe briefly talk about licensing for that repo. Any preferences? GDPL? LGPL as BBB?

**Comment by basisbit** [comment]
personally I don't care, my provided information can be considered CC0 / Public Domain. I also don't think we need an extra repository for this. Maybe an etherpad link would have been enough.
Anyways, please don't forget that this still counts: https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code

Also, I just added some of my own best practices to my initial thread post here.

**Comment by ffdixon** [comment]
If your cool with sending a pull request (and have signed a contributor agreement), we'll gladly merge it in and make it a supported part of the documentation.

**Comment by ichdasich** [comment]
@basisbit yeah, just don't have an etherpad handy. ;-)

@ffdixon I am not sure whether I will be able (time wise) to bring this up to a standard that warrants a pull request. Furthermore, CLAs and me are a difficult storry. ;-) Would spilling it out with CC0/PD so someone with a contributor agreement can just grab it work for you?

**Comment by basisbit** [comment]
Any ideas about what to write regarding how to handle other typical GDPR processes?
- how can the user request a file-download of all the "person-related"/private data from ALL sources including logs and so on
- how can the user request deletion of their "person-related"/private data (**right to erasure**)? How would that work for session recordings? Could students troll their teachers by just requesting deletion of the recording after every recorded session? How could parts of the data be anonymized and recordings be rebuilt instead of full deletion?
- How to anonymize parts of logs of typical BBB setups if a user requests their data deletion but the admin doesn't want to delete all of the logs?
- data processing agreement (DPA) suggestions?
- right to receive personal data in a machine-readable format?

What about required data retention requirements? Are there any for legal reasons?

**Comment by basisbit** [comment]
maybe @ffdixon could provide some insights on how the BBB company handles GDPR related processes for European customers? Do any publicly available tools / scripts exist that help with complying to the process requirements which I mentioned in my previous post in this thread here?

**Comment by ichdasich** [comment]
Some insight there would be good. I actually discussed the deletion/hand-over issues with some of the privacy researchers at my institution. Depending on how privacy preserving you run your setup (for the instance back then, I redirected all logs to /dev/null etc. and did not enforce any user names, i.e., joining rooms was anonymous) this is a really hard task.

Basically, we have no way of verifying that a user who claims to be in a recording actually is in there. We did not really come to a conclusion there apart from 'we will have to do this case-by-case'

**Comment by ichdasich** [comment]
Ok, I finished putting everything I encountered while rooting a BBB setup into https://github.com/ichdasich/bbb-privacy ;

Comments and additions appreciated.

**Comment by ffdixon** [comment]
We took a shot two years ago at writing some scripts to handle a GDPR request (retrieve personal data/deleted personal data) for a recording.  See https://github.com/bigbluebutton/gdpr.  

The script may not work now, but it could should form the basis for creating better support for GDPR in the current version of BigBlueButton.

**Comment by ichdasich** [comment]
Thanks!
One thing that immediately comes to mind is that this most likely will not work with a scalelite setup, where there are no local recordings. Will take a look in the coming days though.

**Comment by basisbit** [comment]
@ichdasich could you please take a look at my first post here in this thread again and include my changes into your documentation? (especially related to the STUN/TURN servers, how to disable event storing + recording + the need to uncomment the line `remove_raw_of_published_recordings`?

**Comment by ichdasich** [comment]
@basisbit ah, missed that you updated it, sorry. Will integrate! The need to uncomment remove_raw... is already in, btw. ;-)

**Comment by ichdasich** [comment]
@basisbit concerning the google stun server in the JS file; are you sure this is being used and not overwritten by /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml ? Just put tcpdump on my link, and did not see any outbound to that host, nor on the corresponding port.

**Comment by basisbit** [comment]
Not sure. That code is quite a mess and I wasn't able to find the code yet, where the Google STUN would be replaced. My guess would be that the Google STUN is used as fallback by the sip.js code.

**Comment by ichdasich** [comment]
Moving this as a problem for tomorrow me; Will retest with a system which does not have anything configured in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

**Comment by prlanzarin** [comment]
@basisbit  @ichdasich If I may chip in on what I can:
  - bbb-webrtc-sfu logs: can be disabled by setting `log.level: none` in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml. No logs will be generated at all, either to stdout, stderr or file.
  - kurento logs: I see you got it covered in the privacy repo. Need any more help, ping me, but setting it to `1` on systemd unit file (location can be found in the output of `sudo systemctl status kurento-media-server`)
  - sip.js's STUN debacle: the Google STUN is hardcoded in the sip.js minified dependency, but **it isn't used in any case**. If the bbb-web STUN/TURN `GET` fails, an empty `iceServers` array is passed to sip.js, which overwrites the default STUN (the one @basisbit pointed out) array. So no STUN server will be used.
  - client side kurento stuff STUN server usage (listen only, screenshare, video): there's a public fallback STUN server pool **which is used if the bbb-web GET fails**. I realise this is not good (pardon, the chunk of that code was made before GDPR was set in stone), and I'll try to make a PR this week to prevent it from using that public STUN server as a fallback.

**Comment by basisbit** [comment]
How about we try to get a first version of the text ready and create a pull request this weekend?

Currently, an introduction to the topic is missing. Maybe something like this could be used for a start:

> In many countries there exist regulation of data protection. For operators of BigBlueButton services, especially private data protection regulations are an important topic. In the European Union the relevant regulation is the [General Data Protection Regulation (GDPR)](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation). Many other countries also adopted similar regulations (for example the [California Consumer Privacy Act (CCPA)](https://en.wikipedia.org/wiki/California_Consumer_Privacy_Act) in California, USA) and some of these regulation even have to be complied with outside of these countries under certain conditions. The following documentation is supposed to help understand where private data gets processed and stored in a typical setup of BigBlueButton, and what configuration options there are.

**Comment by ichdasich** [comment]
Heho,
will try to do the merging of points from above tonight (hopefully). However, I am usually not working on weekends... If you want to, could you maybe do the forking and integrating into the documentation repo?

**Comment by basisbit** [comment]
Sure, can do that. Just please don't sue me any time for copying your text :P Just kidding. Whenever you are done with your changes, just write a notification here, so I know that I can start.

**Comment by ichdasich** [comment]
@basisbit I am mostly done integrating. Should be fine to port now

@prlanzarin Do you have more information on the local fallback for kurento?

**Comment by prlanzarin** [comment]
@ichdasich @basisbit https://github.com/bigbluebutton/bigbluebutton/pull/9623 had to fix some stuff regarding STUN/TURN usage and bolted in the removal of hardcoded 3rd-party fallback STUNs
